Name:           ros-indigo-sr-description
Version:        1.4.0
Release:        0%{?dist}
Summary:        ROS sr_description package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/sr_description
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-position-controllers
Requires:       ros-indigo-robot-mechanism-controllers
Requires:       ros-indigo-urdf
Requires:       ros-indigo-xacro
BuildRequires:  gtest-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-urdf
BuildRequires:  ros-indigo-xacro
BuildRequires:  urdfdom-devel

%description
sr_description contains the description for Shadow Robot's Hand and Arm, as well
as some additional models used in our robot (kinect, etc...).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Apr 07 2015 Shadow Robot's software team <software@shadowrobot.com> - 1.4.0-0
- Autogenerated by Bloom

